default:
  menubar: false
  plugins:
    - link

alternate:
  menubar: false
  selector: textarea.table-editor
  toolbar: styleselect | bold italic | link | alignleft aligncenter alignright | bullist numlist
  plugins:
    - link
    - lists